export const RESERVED_SLUGS = [
  'api',
  'auth',
  'login',
  'register',
  'slug',
  'c',
  'catalogo',
  'producto',
  'productos',
  'admin',
  'dashboard',
  'pcc',
  'backups',
  'static',
  '_next',
  'favicon',
  'favicon-ico',
  'robots-txt',
  'sitemap-xml',
  'manifest-json',
  'service-worker-js',
  'sw-js',
  'nexus',
  'nexusrd',
  'adminer',
  'supabase',
  'storage',
  'rest',
  'realtime',
  'onboarding',
  'configurar',
  'inventario',
  'pedidos',
  'clientes',
  'canje',
  'informes',
  'soporte',
]

export const SLUG_PATTERN = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/
export const SLUG_MAX_LENGTH = 60
export const SLUG_MIN_LENGTH = 1
